[package]
name = "diplom_only_fans_turret"
version = "0.1.0"
edition = "2024"

[dependencies]
tokio = { version = "1.0", features = ["full"] }
axum = { version = "0.8.3", features = ["ws",] }
tower = "0.4"
tower-http = { version = "0.5", features = ["fs", "cors"] }
serde = { version = "1.0", features = ["derive"] }
serde_json = "1.0"
uuid = { version = "1.0", features = ["v4"] }
tracing = "0.1"
tracing-subscriber = "0.3"
tokio-tungstenite = "0.20"
webrtc = "0.8"
futures-util = "0.3"
anyhow = "1.0"
chrono = "0.4.41"
axum-extra = { version = "0.10.1", features = ["cookie"] }