# Cross.toml
[target.arm-unknown-linux-gnueabi]
dockerfile = "Dockerfile.cross"
pre-build = [
    "apt-get update && apt-get install -y  build-essential pkg-config libglib2.0-dev libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev libc6-dev-armhf-cross gcc-arm-linux-gnueabi g++-arm-linux-gnueabi"
]