FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y \
    libgstreamer1.0-dev libgstreamer-plugins-base1.0-dev \
    gstreamer1.0-plugins-base gstreamer1.0-plugins-good \
    gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly \
    gstreamer1.0-libav gstreamer1.0-tools gstreamer1.0-x \
    gstreamer1.0-gl gstreamer1.0-alsa gstreamer1.0-pulseaudio \
    && rm -rf /var/lib/apt/lists/*

WORKDIR /app

COPY target/arm-unknown-linux-musleabihf/release/web_server ./web_server

# Run your app
CMD ["./web_server"]