services:
  web_server:
    image: oleksandrhof/only_fans_turret:arm
    container_name: web_server
    command: ["/app/web_server"]
    environment:
      SERVER_ADDR: "0.0.0.0:8080"
      DEVICE_SERVER_ADDR: "http://192.168.1.13:5001"
      RTP_ADDR: "0.0.0.0:5004"
      RUST_LOG: "info"
    ports:
      - "8080:8080"     # server address
      - "5001:5001"     # gRpc
    restart: no #unless-stopped
    volumes:
      - ./web_config.toml:/app/web_config.toml:ro
    networks:
      - onlyfans_net

networks:
  onlyfans_net:
    driver: bridge