#[target.arm-unknown-linux-gnueabihf]
#linker = "arm-linux-gnueabihf-gcc"
#rustflags = ["-C", "link-args=-L/usr/lib/arm-linux-gnueabihf"]
#ar = "arm-linux-gnueabihf-ar"
#[target.armv7-unknown-linux-gnueabihf]
#linker = "arm-linux-gnueabihf-gcc"
#ar = "arm-linux-gnueabihf-ar"
[target.arm-unknown-linux-gnueabihf]
linker = "/rpi_tools/arm-bcm2708/arm-rpi-4.9.3-linux-gnueabihf/bin/arm-linux-gnueabihf-gcc"
