name: Docker Build & Push

on:
  push:
    branches:
      - main
  workflow_dispatch: # manual trigger

env:
  IMAGE_NAME: only_fans_turret
jobs:
  docker:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repo
      - name: Checkout Repository
        uses: actions/checkout@v5

      - name: Extract Cargo.toml version
        id: cargo_version
        run: |
          VERSION=$(grep '^version' web_server/Cargo.toml | head -n1 | sed -E 's/version\s*=\s*"(.*)"/\1/')
          if [ -z "$VERSION" ]; then
            echo "❌ Cargo version not found"
            exit 1
          fi
          echo "cargo_version=$VERSION" >> $GITHUB_OUTPUT


      - name: Cache cargo registry + target
        uses: actions/cache@v4
        with:
          path: |
            ~/.cargo/registry
            ~/.cargo/git
            target
          key: ${{ runner.os }}-cargo-${{ hashFiles('**/Cargo.lock') }}
          restore-keys: |
            ${{ runner.os }}-cargo-
            

      # Log in to Docker Hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Build Docker image
      - name: Build Docker image
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile
          push: true
          platforms: linux/amd64
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:latest
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:${{ steps.cargo_version.outputs.cargo_version }}
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: false

      - name: Build binary
        uses: houseabsolute/actions-rust-cross@v1
        with:
          command: build
          target: arm-unknown-linux-musleabihf
          args: "--locked --release"
          strip: true

      - name: Build Docker image for ARM
        uses: docker/build-push-action@v6
        with:
          context: .
          file: ./Dockerfile.arm
          push: true
          platforms: linux/arm/v6
          tags: |
            ${{ secrets.DOCKERHUB_USERNAME }}/${{ env.IMAGE_NAME }}:arm
          cache-from: type=gha
          cache-to: type=gha,mode=max
          pull: false

#      - name: Upload binary to server
#        uses: appleboy/scp-action@v1
#        with:
#          host: ${{ secrets.SERVER_HOST }}
#          port: ${{ secrets.PORT }}
#          username: ${{ secrets.SERVER_USER }}
#          key: ${{ secrets.SSH_PRIVATE_KEY }}
#          source: docker-compose.arm.yaml
#          target: ~/${{ env.IMAGE_NAME }}/

      - name: Deploy container to server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          port: ${{ secrets.PORT }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: docker-compose.arm.yaml
          target: ~/${{ env.IMAGE_NAME }}/
          command_timeout: 20m
          script: |
            cd ~/${{ env.IMAGE_NAME }}
            docker compose -f docker-compose.arm.yaml pull
            docker compose -f docker-compose.arm.yaml down
            docker compose -f docker-compose.arm.yaml up -d

            echo "Deployment completed successfully!"